### ISSUE TITLE
PNC exceeds memory during syllable encoding

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#41]
During PNC import, syllable encoding crashes with the following error:
```
neo4j.exceptions.TransientError: There is not enough memory to perform the current task. 
Please try increasing 'dbms.memory.heap.max_size' in the neo4j configuration (normally in 
'conf/neo4j.conf' or, if you you are using Neo4j Desktop, found through the user interface) 
or if you are running an embedded installation increase the heap by using '-Xmx' command 
line flag, and then restart the database.
```

**Comment by msonderegger** [comment]
@james-tanner : this is on roquefort, right?

you should also post here what dbms.memory.heap.max_size currently is in the neo4j conf file, and any info on memory use while enrichment is happening. (Can you tell using `top` whether roquefort's memory is actually being maxed out, or if the issue is the amount of memory available to neo4j (the heap size thing)?)

**Comment by james-tanner** [comment]
@mmcauliffe I guess this is fixed & can be closed now?

**Comment by mmcauliffe** [comment]
Yup!
